### ISSUE TITLE
netopeer not starting 

### ISSUE THREAD

**Issue by cclark1974** [sartura/meta-sysrepo#1]
I'm not having success on getting netopeer started...

I cloned meta-openembedded and I can't find
/home/build/poky/meta-openembedded/meta-efl

root@LEDE:/# /etc/init.d/sysrepo  start
/etc/init.d/sysrepo: .: line 4: can't open '/etc/init.d/functions'
root@LEDE:/# /etc/init.d/netopeer2-server start
/etc/init.d/netopeer2-server: .: line 4: can't open '/etc/init.d/functions'
root@LEDE:/# 

I'm running on top of openwrt

Please advise

**Comment by jsmolic** [comment]
Please try the latest available version
