### ISSUE TITLE
Build error while using the reposistory

### ISSUE THREAD

**Issue by babujin** [sartura/meta-sysrepo#4]
Hi,

we are unable to build the iamge with petalinux tool with this repository,

we are getting this error from last 2 days only, 

we cloned the repository "git clone https://github.com/sartura/meta-sysrepo", we are getting the following error.

![image](https://user-images.githubusercontent.com/85301613/120667811-79644c00-c4ab-11eb-9d6b-5393c91ff2d1.png)

WARNING: libyang-1.0.184+gitAUTOINC+6defee4cab-r0 do_fetch: Failed to fetch URL git://github.com/CESNET/libyang.git;protocol=https, attempting MIRRORS if available
ERROR: libyang-1.0.184+gitAUTOINC+6defee4cab-r0 do_fetch: Fetcher failure: Unable to find revision 6defee4cab9e76bdd736bb3f751de396b4bf5a4b in branch master even from upstream
ERROR: libyang-1.0.184+gitAUTOINC+6defee4cab-r0 do_fetch: Fetcher failure for URL: 'git://github.com/CESNET/libyang.git;protocol=https'. Unable to fetch URL from any source.
ERROR: Logfile of failure stored in: /software/xilinx/petalinux/babuji/Bsp1p2p1Peta/build/tmp/work/aarch64-xilinx-linux/libyang/1.0.184+gitAUTOINC+6defee4cab-r0/temp/log.do_fetch.18518
ERROR: Task (/software/xilinx/petalinux/babuji/Bsp1p2p1Peta/components/ext_sources/meta-sysrepo/recipes-sysrepo/libyang/libyang_git.bb:do_fetch) failed with exit code '1'
WARNING: libssh-0.9.5-r0 do_fetch: Failed to fetch URL git://git.libssh.org/projects/libssh.git;branch=stable-0.9, attempting MIRRORS if available
NOTE: Tasks Summary: Attempted 2581 tasks of which 2554 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /software/xilinx/petalinux/babuji/Bsp1p2p1Peta/components/ext_sources/meta-sysrepo/recipes-sysrepo/libyang/libyang_git.bb:do_fetch
Summary: There were 2 WARNING messages shown.
Summary: There were 2 ERROR messages shown, returning a non-zero exit code.
ERROR: Failed to build project

could you please help me regarding this.

Regards,
N.Babuji

**Comment by synther** [comment]
I believe my PR fixes this https://github.com/sartura/meta-sysrepo/pull/5
